# Generated by Django 4.0.5 on 2022-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hh',
            old_name='text',
            new_name='Edate',
        ),
        migrations.AddField(
            model_name='hh',
            name='Element',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hh',
            name='Sdate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hh',
            name='ch_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hh',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hh',
            name='dose',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hh',
            name='eg_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
