# Generated by Django 4.0.5 on 2022-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotApp', '0002_rename_text_hh_edate_hh_element_hh_sdate_hh_ch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default='')),
                ('Sdate', models.CharField(default='', max_length=255)),
                ('Edate', models.CharField(default='', max_length=255)),
                ('eg_name', models.CharField(default='', max_length=255)),
                ('ch_name', models.CharField(default='', max_length=255)),
                ('Element', models.CharField(default='', max_length=255)),
                ('dose', models.CharField(default='', max_length=255)),
                ('company_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
